
# https://github.com/leoncvlt/loconotion
# anything to contribute back?

# name of the folder inside `dist/` where site will start
name = "building_on_slack"
# ⚠ if you use the old style of shared page link (notion.so/blah-blah), it will go 💥
page = "https://kqu.notion.site/BuildingOnSlack-com-fc3fd8d839ff478ca5f61309b903666a"
theme = "dark"
extension_in_links = false

[site]
[[site.meta]]
name = "title"
content = "Building on Slack"
[[site.meta]]
name = "description"
content = "Learn how others are building on Slack, from small teams to large enterprises."

[[site.inject.body.script]]
data-domain="buildingonslack.com"
src="https://innocuous.idontremember.workers.dev/akgdfdsaf/script.js"
data-api="https://innocuous.idontremember.workers.dev/zzvcvfdfef/event" 
async=""
defer=""

[pages]

